import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import React from "react";
import {SessionProvider} from "next-auth/react"

export default function App({ Component, pageProps }: AppProps) {
    return (
        <SessionProvider>
            <React.Fragment>
                <Head>
                    <title>Facebook-clone</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Component {...pageProps} />
            </React.Fragment>
        </SessionProvider>
    );
}
